---
- name: Mysql DB Initialization Script for New Instances
  hosts: all
  tasks:
    - name: Create Application User
      community.mysql.mysql_user:
        login_host: "{{ db_host }}"
        login_user: "{{ db_root }}"
        login_password: "{{ db_root_pass }}"
        name: "{{ application_user }}"
        host: "{{ item.host }}"
        password: "{{ application_password }}"
        priv: 
          '{{ database }}.*': 'USAGE'
          '{{ database }}.*': 'SELECT, ALTER, CREATE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EXECUTE, INSERT, SHOW VIEW, TRIGGER, UPDATE'
          '*.*': 'LOAD FROM S3'
      with_items:
      - { host: "10.%" }
      
    - name: Create DBA Users
      community.mysql.mysql_user:
        login_host: "{{ db_host }}"
        login_user: "{{ db_root }}"
        login_password: "{{ db_root_pass }}"
        name: "{{ item.name }}"
        host: "{{ item.host }}"
        password: "{{ item.password }}"
        priv: '*.*:GRANT, SELECT, CREATE, CREATE TEMPORARY TABLES, CREATE VIEW, UPDATE, INSERT, ALTER, DELETE, DROP, EXECUTE, SHOW VIEW, TRIGGER, SHOW DATABASES, ALTER ROUTINE, CREATE ROUTINE, CREATE USER, EVENT, INDEX, LOCK TABLES, PROCESS, REFERENCES, RELOAD'
      with_items:
      - { host: "10.10.12.123", name: "randoneering_dba", password: "{{ randoneering_dba_pw }}"}




